
DROP TABLE IF EXISTS Demande_join CASCADE;
DROP TABLE IF EXISTS Admin CASCADE;
DROP TABLE IF EXISTS Participants_Struct CASCADE;
DROP TABLE IF EXISTS Defis CASCADE;
DROP TABLE IF EXISTS Badges CASCADE;
DROP TABLE IF EXISTS Trajets CASCADE;
DROP TABLE IF EXISTS Participants CASCADE;
DROP TABLE IF EXISTS Organisateurs CASCADE;
DROP TABLE IF EXISTS Impact CASCADE;
DROP TABLE IF EXISTS Evenements CASCADE;
DROP TABLE IF EXISTS Structur CASCADE;
DROP TABLE IF EXISTS Adherents CASCADE;
DROP TABLE IF EXISTS Utilisateurs CASCADE;
DROP TABLE IF EXISTS Nom_impact CASCADE;



